// <auto-generated />
using CMGWpf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMGWpf.Migrations
{
    [DbContext(typeof(CmgDbContext))]
    [Migration("20260805135236_AddChordSequenceTable")]
    partial class AddChordSequenceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CMGWpf.Model.Database.ChordSequence", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<double>("BPM")
                        .HasColumnType("REAL");

                    b.Property<string>("Effort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMajor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootNote")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("RootOctave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoundFontFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("chordsequence", (string)null);
                });

        }
    }
}
