// <auto-generated />
using CMGWpf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMGWpf.Migrations
{
    [DbContext(typeof(CmgDbContext))]
    partial class CmgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CMGWpf.Model.Database.Ensemble", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ensemble", (string)null);
                });

            modelBuilder.Entity("CMGWpf.Model.Database.NoteSequence", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("notesequence", (string)null);
                });

            modelBuilder.Entity("CMGWpf.Model.Database.Tag", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("CMGWpf.Model.Database.Voice", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<float>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("PresetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<float>("RegisterHi")
                        .HasColumnType("REAL");

                    b.Property<float>("RegisterLo")
                        .HasColumnType("REAL");

                    b.Property<string>("SoundFontFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timbre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("voice", (string)null);
                });

            modelBuilder.Entity("ensemble_voice", b =>
                {
                    b.Property<string>("ensemble_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("voice_name")
                        .HasColumnType("TEXT");

                    b.HasKey("ensemble_name", "voice_name");

                    b.HasIndex("voice_name");

                    b.ToTable("ensemble_voice", (string)null);
                });

            modelBuilder.Entity("notesequence_tag", b =>
                {
                    b.Property<string>("notesequence_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("tag_name")
                        .HasColumnType("TEXT");

                    b.HasKey("notesequence_name", "tag_name");

                    b.HasIndex("tag_name");

                    b.ToTable("notesequence_tag", (string)null);
                });

            modelBuilder.Entity("ensemble_voice", b =>
                {
                    b.HasOne("CMGWpf.Model.Database.Ensemble", null)
                        .WithMany()
                        .HasForeignKey("ensemble_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMGWpf.Model.Database.Voice", null)
                        .WithMany()
                        .HasForeignKey("voice_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("notesequence_tag", b =>
                {
                    b.HasOne("CMGWpf.Model.Database.NoteSequence", null)
                        .WithMany()
                        .HasForeignKey("notesequence_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMGWpf.Model.Database.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
